services:
  nginx:
    image: nginx:stable
    container_name: edge-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
    restart: unless-stopped
    networks:
      - edge_net
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 5s
      retries: 3

  certbot:
    build:
      context: ./nginx/certbot
    container_name: finance-management-certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - edge_net
    depends_on:
      - nginx

networks:
  edge_net:
    name: edge_net
    driver: bridge
    attachable: true
