services:
  finance-management-web:
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:${WEB_PORT}}
      BASE_URL: ${BASE_URL:-http://localhost:${WEB_PORT}}

  finance-management-api:
    environment:
      NODE_ENV: development
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:${WEB_PORT}}

  finance-management-db:
    profiles:
      - local-db
