services:
  finance-management-web:
    ports:
      - "${WEB_PORT:-3000}:3000"

  finance-management-api:
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD:-example}@finance-management-db:27017/${MONGO_DATABASE:-finance-management}?authSource=admin}
    ports:
      - "${API_PORT:-5000}:5000"

  finance-management-db:
    profiles: ["local-db"]
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-finance-management}
    volumes:
      - finance-management-mongo-data:/data/db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
          pids: 256
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    healthcheck:
      test:
        - "CMD-SHELL"
        - >-
          mongosh --host 127.0.0.1 --username "$$MONGO_INITDB_ROOT_USERNAME" --password "$$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - finance-management_net

volumes:
  finance-management-mongo-data:
    driver: local
